version: '3.7'

services:
  db-service:
    image: "mysql:8.0"
    restart: always
    container_name: manager-account-db
    environment:
      MYSQL_DATABASE: manager-account-db
      MYSQL_USER: manager-account
      MYSQL_PASSWORD: manager-account
      MYSQL_ROOT_PASSWORD: manager-account
    ports:
      - "6612:3306"
    networks:
      - local-network
    depends_on:
      - db-service

  app-service:
    build:
      context: .
      dockerfile: Dockerfile
    image:
      manager-account:latest
    container_name: manager-account-app
    environment:
      DB_USERNAME: manager-account
      DB_PASSWORD: manager-account
      DB_ENDPOINT: jdbc:mysql://db-service:6612/manager-account?useSSL=false
    ports:
      - "9090:9090"
    networks:
      - local-network
    depends_on:
      - db-service

networks:
  local-network:
    driver: bridge