micronaut:
  application:
    name: managerAccount
  server:
    port: 9090
    cors:
      enabled: true
      configurations:
        all:
          allowedMethods:
            - POST
            - PATCH
            - OPTIONS
            - GET
datasources:
  default:
    url: ${DB_ENDPOINT}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: false
flyway:
  datasources:
    default:
      enabled: true